### ISSUE TITLE
Inverted on/off_payload when discovery option used

### ISSUE THREAD

**Issue by a-x-** [flyte/mqtt-io#104]
Me and folks in homeassistant thread #82 have to [invert on and off payloads](https://github.com/flyte/pi-mqtt-gpio/issues/82#issuecomment-591642263)

**Comment by flyte** [comment]
Thanks for the separate Issue. I'll add this to the list of things to review before the next release.

**Comment by flyte** [comment]
I'm interested to know if this is still an issue with the new version in #178 . Could you please test it out and let me know? Cheers

**Comment by BenjiU** [comment]
closed due to missing response
