### ISSUE TITLE
MQTT Client IDs the same in multiple instances - info

### ISSUE THREAD

**Issue by jaburges** [flyte/mqtt-io#110]
Hi there, 
Not sure how the client ID is generated but using 1 instance on a pi zero W for a Dryer door switch, and now looking at making a doorbell button & camera on a pi 4. 
However Client ID is the same and thus kick each other off the MQTT broker. 
```
1590335228: New connection from 192.168.1.181 on port 1883.
1590335228: Client pi-mqtt-gpio-bd40af270ac16730956339447e5c734a934f34be already connected, closing old connection.
1590335228: Client pi-mqtt-gpio-bd40af270ac16730956339447e5c734a934f34be disconnected.
1590335228: New client connected from 192.168.1.181 as pi-mqtt-gpio-bd40af270ac16730956339447e5c734a934f34be (c0, k60, u'<user>').
1590335229: New connection from 192.168.1.182 on port 1883.
1590335229: Client pi-mqtt-gpio-bd40af270ac16730956339447e5c734a934f34be already connected, closing old connection.
1590335229: Client pi-mqtt-gpio-bd40af270ac16730956339447e5c734a934f34be disconnected.
1590335229: New client connected from 192.168.1.182 as pi-mqtt-gpio-bd40af270ac16730956339447e5c734a934f34be (c0, k60, u'<user>').
1590335230: Client pi-mqtt-gpio-bd40af270ac16730956339447e5c734a934f34be disconnected.
1590335230: New connection from 192.168.1.181 on port 1883.
1590335230: Client pi-mqtt-gpio-bd40af270ac16730956339447e5c734a934f34be disconnected.
1590335230: New client connected from 192.168.1.181 as pi-mqtt-gpio-bd40af270ac16730956339447e5c734a934f34be (c0, k60, u'<user>').
```

`client_id` is a config option, but I couldn't see it in the instructions (not to say it isnt there, i may have missed it) - but found it in your code (nice work!) and made a PR for the `Readme.md` to add if you want.
(Not sure if the code is designed to randomly generate another `client_id`, if it is that wasnt working for me)
Thanks for sharing your work!

**Comment by flyte** [comment]
Thank for the info @jaburges 

I'll add a review of the client ID generation to our list of tasks for the next release.
