### ISSUE TITLE
Support for ModMyPi PiOT Relay Board

### ISSUE THREAD

**Issue by claudegel** [flyte/mqtt-io#126]
Does it support this relay board, ModMyPi PiOT Relay Board

**Comment by BenjiU** [comment]
Not complete: the relays are only attached to the gpios, that would work. But the relay board has some startup handshaking, that isn't supported yet.

**Comment by claudegel** [comment]
OK if I ever receive my order for that part I'll test it and send a patch if I succeed.

Thank you
