### ISSUE TITLE
cannot install on raspbian rpi4 latest

### ISSUE THREAD

**Issue by claudegel** [flyte/mqtt-io#127]
When I run pip3 install pi-mqtt-gpio I get the following error
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://www.iwheels.org/simple/cerberus.
Do I need to install other dependency ?

**Comment by claudegel** [comment]
Cerberus is missing ?

**Comment by zellneralex** [comment]
It seams like all versions of cerberus get deleted from www.piwheels.org

**Comment by claudegel** [comment]
Ok I've copied over from another pi de cerberus  and Cerberus-1.3.2.egg-info dir and it is working. I still have an issue with auto startup at boot, see #129 above.

**Comment by g8ry** [comment]
add this line to your /etc/pip.conf

`--extra-index-url=https://pypi.org/project`

then execute

`pip3 install Cerberus`

**Comment by claudegel** [comment]
That work. I was able to install Cerberus.
