### ISSUE TITLE
Add Wifi Strength

### ISSUE THREAD

**Issue by g8ry** [flyte/mqtt-io#130]
Would it be possible to add the Pi's current Wifi strength sent via MQTT on a regular interval.

**Comment by flyte** [comment]
Hmm, I suspect there's a better tool for this job. Since we're talking about MQTT, another process could run, or use cron, periodically publishing telemetry about the Pi, such as its Wi-Fi signal strength, CPU temps etc.

I don't think it's something suitable for inclusion in this project.
