### ISSUE TITLE
Why readme don’t include discovery config description any more?

### ISSUE THREAD

**Issue by a-x-** [flyte/mqtt-io#147]
Also I remember, pi-mqtt-gpio config had something like home assistant [device classes](https://www.home-assistant.io/integrations/binary_sensor/), but I cannot find them now

**Comment by flyte** [comment]
I've had a search through the whole commit history and not found any information about discovery in the readme. I suppose it just never got written.

We don't, and never have had any device classes, and I can't really think what you have seen that might have been similar I'm afraid. What do you think would be the use case of having device classes on this project?
