### ISSUE TITLE
BH1750 readings are incorrect

### ISSUE THREAD

**Issue by Meep0815** [flyte/mqtt-io#189]
I think the readings of a bh1750 sensor are incorrect due to wrong implementation of the sensor.
I cross checked with two sensor modules. Both reported 800 - 3000 lux where other sensors I have report 8 - 12 lux.

Changing the implementation of get_value() in bh1750.py from:

 ```
def get_value(self, sens_conf: ConfigType) -> SensorValueType:
        """
        Get the light value from the sensor.
        """
        with self.SMBus(self.bus_num) as bus:
            return float(bus.read_word_data(self.address, ONE_TIME_HIGH_RES_MODE_1)) / 1.2
```

to:

```
def get_value(self, sens_conf: ConfigType) -> SensorValueType:
        with self.SMBus(self.bus_num) as bus:
            data = bus.read_i2c_block_data(self.address, ONE_TIME_HIGH_RES_MODE_1, 2)
            result = (data[1] + (256 * data[0])) / 1.2 
            return float(result) 

```
fixes this issue for me.

The change was copied from http://raspberrypi.link-tech.de/doku.php?id=bh1750 
Sorry I do not know nice code style.

**Comment by flyte** [comment]
Thanks @Meep0815 ! I've applied the fix and I'll release a new version shortly.
