### ISSUE TITLE
No data Being sent across

### ISSUE THREAD

**Issue by BatGirl26** [flyte/mqtt-io#22]
Now, I'm trying to use your Service, but as of yet, I cannot get it to send data across to the Subscribing service.  I have tested the Publish script I have and I am able to Publish and subscribe using the Normal mosquito Client. But your service is not working to send the data across and turn on the GPIO pins. I'm not getting any error messages and it's just sitting there with the message:
MQTT client: Sending PINGREQ
MQTT cleint: Receiving PINGRESP
Now, this is all its doing when I send the message to turn on the GPIO's. I'm new to this, could I please get some tips, please. Is there a step im missing ?

**Comment by flyte** [comment]
Hi, could you let me know which topics you're publishing to with what payloads, and paste a copy of your config file please?

**Comment by flyte** [comment]
Closing this for now but feel free to open it again with the info requested above.
