### ISSUE TITLE
mqtt-io with arduino

### ISSUE THREAD

**Issue by X-Renegade-X** [flyte/mqtt-io#230]
Hi,
is there any possibility to connect an arduino over I2C on mqtt-io to send the mqtt commands over the raspberry?

greets
Rene

**Comment by BenjiU** [comment]
Hi, no, i don't think that is a suitable way :-D
You would have to create a i2c "protocol" for the data you need from your arduino i2c slave (e.g. byte 1 is "date from sensor A", byte 2 is "data from sensor B" etc. Then you would have to write a i2c driver for that in python, so we can include it in mqtt-io project.
