### ISSUE TITLE
Is there the same project for arduino?

### ISSUE THREAD

**Issue by a-x-** [flyte/mqtt-io#239]
Would be awesome expose gpio pins on arduino with Ethernet shield 

**solution I'd like**
C++ firmware project with mqtt-io like config. 
Config might be saved at build time and via integrated web server
Storing of config might be implemented via EEPROM Write

**alternatives I've considered**
- Write every firmware manually 
- Don’t use arduino and to suffer with wifi 
- Create the project myself 

**Additional context**
I love Pi-mqtt-gpio and ESPHome. And now I want to reach both  microcontroller’s (vs raspberry) and Ethernet (vs wifi) stability. Also, I want to keep using easy to go configs instead of tons of C++ code, that looses readability

**Comment by BenjiU** [comment]
Yeah, no one found something similar? I'll close it, after this issue got one year old 🎂  this week.
