### ISSUE TITLE
feature request: retain inputs

### ISSUE THREAD

**Issue by huckpdx** [flyte/mqtt-io#27]
I just discovered your service and am testing it. I see that you recently added the option to configure outputs with retain = true. It would be great to have this option for inputs. 

In my case, I'm using node-red. when I redeploy a flow, the client session is reset, and I don't get input status until it changes state. some of my sensors only change twice a day, so this is a problem for me.

Thanks for considering this request.

**Comment by flyte** [comment]
Sounds good to me! I'll add that in this week. Cheers!

**Comment by flyte** [comment]
@huckpdx I've implemented this in the `develop` branch. I'm on a train and don't have the ability to test it right now, so I can't release a new version yet. Please test it out from the repository and let me know how it goes.

Cheers!

**Comment by jfiger** [comment]
Is the feature "retain inputs" already implemented? Not working for me.
