### ISSUE TITLE
How to run when outside project directory?

### ISSUE THREAD

**Issue by codeclinic** [flyte/mqtt-io#307]
Hi,

How can we run this script from outside the project directory?

I really need to run this automatically at boot via crontab, but I can't figure out the correct command to get this to run unless I'm directly inside the project directory.

No matter what I try it just outputs the following:
`/python3: No module named mqtt_io`

Thanks.

**Comment by BenjiU** [comment]
Please provide more information in your paths. What ist outside? Are you using virtualenv? Would supervisor be a solution for you?

**Comment by codeclinic** [comment]
I'm not using venv or supervisor. Just cloned the project to a local directory and then run the project as described in the readme.

If I navigate to any other directory/folder I am unable to run the script.

**Comment by BenjiU** [comment]
Hi @codeclinic,

if this is still relevant, please post your command lines.
