### ISSUE TITLE
Version 2.2.9 is not available on PyPI

### ISSUE THREAD

**Issue by ondras12345** [flyte/mqtt-io#322]
It has been 2 days since the release was published on Github, so I assume it would already be on PyPI if everything was working right.
https://pypi.org/project/mqtt-io/#history

Apparently the "Publish to PyPI" action was skipped: https://github.com/flyte/mqtt-io/actions/runs/5530576216

**Comment by lloydbayley** [comment]
Any joy here? Would like to upgrade!

**Comment by BenjiU** [comment]
Hey, it's sonerhing with the tag variable in the pipeline. I'll try to fix it today. Next three days I'm going to be on a workshop and won't be available...

**Comment by BenjiU** [comment]
@ondras12345 @lloydbayley
2.2.9 should be availabe on pypi.org now. May you please have a look at it and verify if it is working?

Thanks!
Benni

**Comment by lloydbayley** [comment]
> @ondras12345 @lloydbayley 2.2.9 should be availabe on pypi.org now. May you please have a look at it and verify if it is working?
> 
> Thanks! Benni

It is indeed there! Thank you very much!
Always nice when you can say "It VERKS!" :)
