### ISSUE TITLE
Install Error when running: python -m pi_mqtt_gpio.server config.yml

### ISSUE THREAD

**Issue by smoonlee** [flyte/mqtt-io#34]
![image](https://user-images.githubusercontent.com/22956963/40750556-9b33228e-645f-11e8-9cc8-03ab6231aaf4.png)

**Comment by flyte** [comment]
Hi @smoonlee 

Please make sure you create a configuration file as per [this section](https://github.com/flyte/pi-mqtt-gpio#configuration) of the readme.

The software is complaining that it can't find the configuration file, so presumably it hasn't been created yet.

**Comment by smoonlee** [comment]
Cheers Ellis got it working 👍
