### ISSUE TITLE
Where's inputs?

### ISSUE THREAD

**Issue by coogle** [flyte/mqtt-io#37]
Hello,

Am I missing something? I have a topic '/my/prefix' and a few GPIO pins setup. I can publish to `/my/prefix/output/fan/set` and it works, but I don't see any corresponding state in `/my/prefix/input/fan`

I would expect that I could see both the current state and set the state of a GPIO pin using these but I'm not sure where my inputs are...

**Comment by flyte** [comment]
Hi @coogle 

When you publish to `/my/prefix/output/fan/set`, once the Pi has set that output, it will publish the new value on `/my/prefix/output/fan`.

The `input` and `output` in this case, is in relation to the physical input/output pins of the Pi, so for example, if you had a switch connected, that could publish to `/my/prefix/input/switch` when it changes state.

Hope that helps!

**Comment by flyte** [comment]
Hey @coogle I'm going to close this for now, assuming that answered your question. Please feel free to reopen the issue if you're still having problems. Cheers
