### ISSUE TITLE
question: refresh sensor values without retain?

### ISSUE THREAD

**Issue by vontrapp** [flyte/mqtt-io#39]
The retain flag is the straightforward way to persist sensor data to be retrieved later, such as when a service looking at the status is restarted, it can obtain the "current" state. 

This however is insufficient when you would like to ensure that the state you have *is* actually a really real current state, and not something stale that has simply failed to have been updated. 

I suppose I could check the LWT status and then status all the sensors as "stale" if it's dead but that would be a lot of extra logic and duplicated for each and every sensor as well. 

It would be nice if one or both of the following could be added (and I'd be willing to contribute code even) 

a) a configuration option (global or per sensor) to send unsolicited sensor updates. In real life this might look like "pio/inputs/garage_door_closed = true" every 5 minutes or whatever. 

b) respond to a new topic, "pio/query/garage_door_open" which would then trigger a fresh publish of the above topic on demand. It could even respond to "pio/query/" by publishing the current state of *all* inputs.

**Comment by flyte** [comment]
@vontrapp I see what you mean.

LWT is indeed the canonical way to handle this, but I agree that it's tricky to integrate, especially with existing third party systems.

Option A sounds easiest to implement, and least confusing to configure.

**Comment by vontrapp** [comment]
Turns out after actually getting these into HA with LWT, it is actually quite straightforward and integrated already, with sane defaults, to mark 'stale' ("unavailable") sensors with very little configuration.

**Comment by flyte** [comment]
Yeah, LWT works well with Home Assistant. I'll close this now then, since there's a viable solution.
