### ISSUE TITLE
Support digital sensors, as opposed to just IO expanders

### ISSUE THREAD

**Issue by tarbax** [flyte/mqtt-io#40]
i want to hook up these: 4x DS18b20, TCR5000(pulse counter),BMP280, BH1750, HC-SR04, read Switch and 1 current sensor

is this possible ?
i cant find any info what is supported.

**Comment by flyte** [comment]
Hi @tarbax 

Currently only the modules listed here https://github.com/flyte/pi-mqtt-gpio#modules are supported.

The modules you list are temperature sensors, pulse counters, barometric sensors, light sensors, and ultrasonic sensors. So far, the modules supported on this project are digital/analogue IO expander chips, but it may be possible to write a module for these chips somehow (I'd probably have to reassess the architecture slightly).

It'll have to go down as a feature request at the moment, and I'll work on it when I've got some time, or if you would like to write the code, let's discuss how it might look.

**Comment by Wafje** [comment]
Hi. I'm also interested in DS18b20 support over one wire.

**Comment by flyte** [comment]
The work to implement digital sensors has been completed by @BenjiU allowing modules to be created for individual sensors you'd like to support. I don't have any of those listed, but if you're capable, then I'll happily accept pull requests for modules that you've made.
