### ISSUE TITLE
PCF8574 & server crash

### ISSUE THREAD

**Issue by eXCepT74** [flyte/mqtt-io#45]
please delete - problem solved

**Comment by flyte** [comment]
That was easy :)

**Comment by flyte** [comment]
Out of interest though, what was the solution?

**Comment by eXCepT74** [comment]
The problem was server crashing when was used PCF8574 extender. I wrote config with multiple inputs. And after start server crashed. Then for find the problem - i removed all inputs except one - restart and server crashed :( .
So i changed inputs to outputs - restart and all was ok. In one word  - if server worked as inputs never started just crashed with many lines - here on this page was full log for 15 minutes ;).
Finally i solved problem - some i2c component from rpi3 was hang i think. Restart solved problem.
I dont wanted to bother you. I doing full smarthome project on your code. I use as well Tasmota firmware and homekit2MQTT. I will use manu inputs and outputs by GPIOs and PCF expanders that i think we will speak many times ;) .  I see that you already like it ;).
Ok no more jokes. Good job mate !
