### ISSUE TITLE
DS18B20 support

### ISSUE THREAD

**Issue by patvdleer** [flyte/mqtt-io#54]
Request for support for the DS18B20;

https://github.com/flyte/pi-mqtt-gpio/issues/32#issuecomment-465640303

No, as far as I know, one wire from dht11 and one wire from ds18b20 are incompatible. So you should create a new issue for ds18b20, if you want it to be supported. Maybe you could try a library, that should be supported and mention it there. (e.g. https://github.com/timofurrer/w1thermsensor)

**Comment by patvdleer** [comment]
I made a very crude and untested setup, not sure this is the way to go https://github.com/patvdleer/pi-mqtt-gpio/commit/f701a239c9a65804ce4c4358569e4a510f452c68

**Comment by blademckain** [comment]
me too need supporto for DS18B20
+1

**Comment by eXCepT74** [comment]
Me too and even multi sensor config - multiple on one line as in Tasmota sonoff firmware. I have in plan i2c bus in my house and I have few rooms to check temperature and many open/close / motion  sensors. To extend range I’ll use this:

https://www.sparkfun.com/products/14589

**Comment by ViPeR5000** [comment]
+1

**Comment by Alycee1993** [comment]
Is this happening ?

**Comment by BenjiU** [comment]
Should be fixed with PR above
