### ISSUE TITLE
Can PCF8574 be daisy chained ?

### ISSUE THREAD

**Issue by c3reeman** [flyte/mqtt-io#60]
Can PCF8574 be daisy chained ? Ideally I need 45 ish gpio’s from one raspberry pi I see this version below looks like you can simply plug them together ??

WAVGAT PCF8574 IO Expansion Board I2C-Bus Evaluation Development Module Hot Sale
https://s.click.aliexpress.com/e/BYxFsOy

**Comment by flyte** [comment]
Hey, yes they can. There are three address pins, which will allow you to address up to 8 pcf8574 chips, so that should give you 64 IO pins in theory.
