### ISSUE TITLE
ds18b20

### ISSUE THREAD

**Issue by ViPeR5000** [flyte/mqtt-io#69]
add support to  ds18b20

**Comment by ViPeR5000** [comment]
MQTT client: Sending SUBSCRIBE (d0, m2) [('home/octopi/output/Ender-Luzes/set', 1)]
MQTT client: Sending PUBLISH (d0, q0, r1, m1), 'home/octopi/input/Ender-Luzes', ... (3 bytes)
Subscribed to topic: 'home/octopi/output/Ender-Luzes/set'
MQTT client: Sending SUBSCRIBE (d0, m3) [('home/octopi/output/Ender-Luzes/set_on_ms', 1)]
Subscribed to topic: 'home/octopi/output/Ender-Luzes/set_on_ms'
MQTT client: Sending SUBSCRIBE (d0, m4) [('home/octopi/output/Ender-Luzes/set_off_ms', 1)]
Subscribed to topic: 'home/octopi/output/Ender-Luzes/set_off_ms'

**Comment by flyte** [comment]
Support has been added by #80 and will be released in the next version of the software.
