### ISSUE TITLE
Momentary vs rocker switch?

### ISSUE THREAD

**Issue by pasleto** [flyte/mqtt-io#70]
Hi, am i able to  connect rocker switch as digital input, or only momentary push button? 

Thanks for the answer :)

**Comment by BenjiU** [comment]
Just to be sure: rocker switch means, that it holds its position/state (ON or OFF), until you press it again to opposite state (OFF or ON)?
Shouldn't be a problem. I have this for my light switches.

**Comment by flyte** [comment]
Yes, absolutely. Any switch should be suitable. It just pulls the input pin from high to low, or low to high, depending how it's set up.

**Comment by reestr** [comment]
I have this same question, how would someone actually configure this though; on receiving an mqtt message drive a GPIO pin from low -> high (1 second) -> low ?

**Comment by BenjiU** [comment]
Hi reestr, I don't get your point in total: are you talking about a output? The original question was about an input.

**Comment by reestr** [comment]
> Hi reestr, I don't get your point in total: are you talking about a output? The original question was about an input.

You're right, I missed the part about it being for input, sorry for the noise.  I was talking about output, and the same request seems to have been captured [here](https://github.com/flyte/pi-mqtt-gpio/issues/38).
